name: dagger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy & Test Full Stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Full-Stack Pipeline
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          module: github.com/BRicsi02/dagger-demo/.dagger/src/dagger_demo@main
          args: deploy-full-stack --src=app
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
